/*
 * Copyright 2016 james.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalTime;
import static java.time.temporal.TemporalAdjusters.next;
import java.util.ArrayList;
import org.jopendocument.dom.spreadsheet.Sheet;
/**
 *
 * @author james
 */
public class lgExport extends javax.swing.JDialog 
{
    main parent;
    dbConnection connection;
    commonFunctions comFunc;
    ArrayList<lifeguards> guardShifts = new ArrayList<lifeguards>();
    String defaultSUP;
    LocalTime openTime = LocalTime.of(5, 00);
    LocalTime twoPm = LocalTime.of(14, 00);
    LocalTime satSunOpenTime = LocalTime.of(6, 00);
    LocalTime satSunClose = LocalTime.of(19, 00);
    LocalTime monThursClose = LocalTime.of(20, 30);
    LocalTime onePm = LocalTime.of(13,00);
    LocalTime elevenThirty = LocalTime.of(11, 30);
    LocalTime eightThirty = LocalTime.of(8, 30);
    LocalTime threePm = LocalTime.of(15, 00);
    LocalTime fourPm = LocalTime.of(16, 00);
    LocalTime fivePm = LocalTime.of(17, 00);
    LocalTime tenThirty = LocalTime.of(10, 30);
    LocalTime twelveThirty = LocalTime.of(12, 30);
    LocalTime sevenPm = LocalTime.of(19, 00);
    
    String [] [] timeList = new String [33] [3];
    /**
     * Creates new form lgExport
     */
    public lgExport(main inParent, dbConnection inConnection, commonFunctions inCommon, String inDefaultSUP) {
        super(inParent,true);
        initComponents();
        parent = inParent;
        connection = inConnection;
        comFunc = inCommon;
        defaultSUP = inDefaultSUP;
        loadData();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mondayGroup = new javax.swing.ButtonGroup();
        tuesdayGroup = new javax.swing.ButtonGroup();
        wednesdayGroup = new javax.swing.ButtonGroup();
        thursdayGroup = new javax.swing.ButtonGroup();
        fridayGroup = new javax.swing.ButtonGroup();
        dateCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        exportButton = new javax.swing.JButton();
        mondayDefRdBttn = new javax.swing.JRadioButton();
        mondayOtherRdBttn = new javax.swing.JRadioButton();
        supMondayTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tuesdayOtherRdBttn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        supTuesdayTextField = new javax.swing.JTextField();
        tuesdayDefRdBttn = new javax.swing.JRadioButton();
        wednesdayDefRdBttn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        wednesdayOtherRdBttn = new javax.swing.JRadioButton();
        supFridayTextField = new javax.swing.JTextField();
        supWednesdayTextField = new javax.swing.JTextField();
        fridayDefRdBttn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        thursdayDefRdBttn = new javax.swing.JRadioButton();
        thursdayOtherRdBttn = new javax.swing.JRadioButton();
        supThursdayTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fridayOtherRdBttn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LG Roster Exporter");

        dateCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateComboItemStateChanged(evt);
            }
        });
        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });

        jLabel1.setText("SUP selector:");

        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        mondayGroup.add(mondayDefRdBttn);
        mondayDefRdBttn.setSelected(true);
        mondayDefRdBttn.setText("Default");

        mondayGroup.add(mondayOtherRdBttn);
        mondayOtherRdBttn.setText("Other");
        mondayOtherRdBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayOtherRdBttnActionPerformed(evt);
            }
        });

        jLabel4.setText("Monday:");

        tuesdayGroup.add(tuesdayOtherRdBttn);
        tuesdayOtherRdBttn.setText("Other");
        tuesdayOtherRdBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayOtherRdBttnActionPerformed(evt);
            }
        });

        jLabel5.setText("Tuesday:");

        tuesdayGroup.add(tuesdayDefRdBttn);
        tuesdayDefRdBttn.setSelected(true);
        tuesdayDefRdBttn.setText("Default");

        wednesdayGroup.add(wednesdayDefRdBttn);
        wednesdayDefRdBttn.setSelected(true);
        wednesdayDefRdBttn.setText("Default");

        jLabel6.setText("Friday:");

        wednesdayGroup.add(wednesdayOtherRdBttn);
        wednesdayOtherRdBttn.setText("Other");
        wednesdayOtherRdBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayOtherRdBttnActionPerformed(evt);
            }
        });

        fridayGroup.add(fridayDefRdBttn);
        fridayDefRdBttn.setSelected(true);
        fridayDefRdBttn.setText("Default");

        jLabel7.setText("Wednesday:");

        thursdayGroup.add(thursdayDefRdBttn);
        thursdayDefRdBttn.setSelected(true);
        thursdayDefRdBttn.setText("Default");

        thursdayGroup.add(thursdayOtherRdBttn);
        thursdayOtherRdBttn.setText("Other");
        thursdayOtherRdBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayOtherRdBttnActionPerformed(evt);
            }
        });

        jLabel8.setText("Thursday:");

        fridayGroup.add(fridayOtherRdBttn);
        fridayOtherRdBttn.setText("Other");
        fridayOtherRdBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayOtherRdBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wednesdayDefRdBttn)
                                            .addComponent(wednesdayOtherRdBttn))
                                        .addGap(18, 18, 18)
                                        .addComponent(supWednesdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mondayDefRdBttn)
                                            .addComponent(mondayOtherRdBttn))
                                        .addGap(18, 18, 18)
                                        .addComponent(supMondayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tuesdayDefRdBttn)
                                            .addComponent(tuesdayOtherRdBttn))
                                        .addGap(18, 18, 18)
                                        .addComponent(supTuesdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(thursdayDefRdBttn)
                                            .addComponent(thursdayOtherRdBttn))
                                        .addGap(18, 18, 18)
                                        .addComponent(supThursdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fridayDefRdBttn)
                                            .addComponent(fridayOtherRdBttn))
                                        .addGap(18, 18, 18)
                                        .addComponent(supFridayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mondayDefRdBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(supMondayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mondayOtherRdBttn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(thursdayDefRdBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(supThursdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thursdayOtherRdBttn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tuesdayDefRdBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supTuesdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tuesdayOtherRdBttn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fridayDefRdBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supFridayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fridayOtherRdBttn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wednesdayDefRdBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supWednesdayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wednesdayOtherRdBttn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadData()
    {
        LocalDate myDate = null;
        LocalDate tempDate = LocalDate.now();
        try
        {
            myDate = tempDate.with(next(DayOfWeek.SATURDAY));
            dateCombo.addItem(comFunc.formatDate(myDate));
            dateCombo.addItem(comFunc.plusDaysFormated(myDate, 7));
            dateCombo.addItem(comFunc.plusDaysFormated(myDate, 14));
            dateCombo.addItem(comFunc.plusDaysFormated(myDate, 21));
        
            //Add time data to array    
            //Row 1
            timeList[0][0] = "05:00";
            timeList[0][1] = "27";
            timeList[0][2] = "86";
            //Row 2
            timeList[1][0] = "05:30";
            timeList[1][1] = "28";
            timeList[1][2] = "87";
            //Row 3
            timeList[2][0] = "06:00";
            timeList[2][1] = "29";
            timeList[2][2] = "88";
            //Row 4
            timeList[3][0] = "06:30";
            timeList[3][1] = "30";
            timeList[3][2] = "89";
            //Row 5
            timeList[4][0] = "07:00";
            timeList[4][1] = "31";
            timeList[4][2] = "90";
            //Row 6
            timeList[5][0] = "07:30";
            timeList[5][1] = "32";
            timeList[5][2] = "91";
            //Row 7
            timeList[6][0] = "08:00";
            timeList[6][1] = "33";
            timeList[6][2] = "92";
            //Row 8
            timeList[7][0] = "08:30";
            timeList[7][1] = "34";
            timeList[7][2] = "93";
            //Row 9
            timeList[8][0] = "09:00";
            timeList[8][1] = "35";
            timeList[8][2] = "94";
            //Row 10
            timeList[9][0] = "09:30";
            timeList[9][1] = "36";
            timeList[9][2] = "95";
            //Row 11
            timeList[10][0] = "10:00";
            timeList[10][1] = "37";
            timeList[10][2] = "96";
            //Row 12
            timeList[11][0] = "10:30";
            timeList[11][1] = "38";
            timeList[11][2] = "97";
            //Row 13
            timeList[12][0] = "11:00";
            timeList[12][1] = "39";
            timeList[12][2] = "98";
            //Row 14
            timeList[13][0] = "11:30";
            timeList[13][1] = "40";
            timeList[13][2] = "99";
            //Row 15
            timeList[14][0] = "12:00";
            timeList[14][1] = "41";
            timeList[14][2] = "100";
            //Row 16
            timeList[15][0] = "12:30";
            timeList[15][1] = "42";
            timeList[15][2] = "101";
            //Row 17
            timeList[16][0] = "13:00";
            timeList[16][1] = "43";
            timeList[16][2] = "102";
            //Row 18
            timeList[17][0] = "13:30";
            timeList[17][1] = "44";
            timeList[17][2] = "103";
            //Row 19
            timeList[18][0] = "14:00";
            timeList[18][1] = "45";
            timeList[18][2] = "104";
            //Row 20
            timeList[19][0] = "14:30";
            timeList[19][1] = "46";
            timeList[19][2] = "105";
            //Row 21
            timeList[20][0] = "15:00";
            timeList[20][1] = "47";
            timeList[20][2] = "106";
            //Row 22
            timeList[21][0] = "15:30";
            timeList[21][1] = "48";
            timeList[21][2] = "107";
            //Row 23
            timeList[22][0] = "16:00";
            timeList[22][1] = "49";
            timeList[22][2] = "108";
            //Row 24
            timeList[23][0] = "16:30";
            timeList[23][1] = "50";
            timeList[23][2] = "109";
            //Row 25
            timeList[24][0] = "17:00";
            timeList[24][1] = "51";
            timeList[24][2] = "110";
            //Row 26
            timeList[25][0] = "17:30";
            timeList[25][1] = "52";
            timeList[25][2] = "111";
            //Row 27
            timeList[26][0] = "18:00";
            timeList[26][1] = "53";
            timeList[26][2] = "112";
            //Row 28
            timeList[27][0] = "18:30";
            timeList[27][1] = "54";
            timeList[27][2] = "113";
            //Row 29
            timeList[28][0] = "19:00";
            timeList[28][1] = "55";
            timeList[28][2] = "114";
            //Row 30
            timeList[29][0] = "19:30";
            timeList[29][1] = "56";
            timeList[29][2] = "115";
            //Row 31
            timeList[30][0] = "20:00";
            timeList[30][1] = "57";
            timeList[30][2] = "116";
            //Row 32
            timeList[31][0] = "20:30";
            timeList[31][1] = "58";
            timeList[31][2] = "117";
            //Row 33
            timeList[32][0] = "21:00";
            timeList[32][1] = "59";
            timeList[32][2] = "118";
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
        
    }
    private void mondayOtherRdBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayOtherRdBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayOtherRdBttnActionPerformed

    private void tuesdayOtherRdBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayOtherRdBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tuesdayOtherRdBttnActionPerformed

    private void wednesdayOtherRdBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayOtherRdBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayOtherRdBttnActionPerformed

    private void thursdayOtherRdBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayOtherRdBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thursdayOtherRdBttnActionPerformed

    private void fridayOtherRdBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayOtherRdBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fridayOtherRdBttnActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        Sheet guardSheet = comFunc.loadTemplate("roster");
        LocalDate outDate = (comFunc.dateSwitch((String)dateCombo.getSelectedItem())).toLocalDate();
        
        java.sql.Date myDate = comFunc.dateSwitch((String)dateCombo.getSelectedItem());
        LocalDate startDate = myDate.toLocalDate();
        // write saturday values
        guardSheet = writeSaturday(myDate, guardSheet);
        LocalDate tempDate = myDate.toLocalDate().plusDays(1); //get sunday date
        myDate = java.sql.Date.valueOf(tempDate);
        // write sunday values
        guardSheet = writeSunday(myDate, guardSheet);
        tempDate = myDate.toLocalDate().plusDays(1); //get monday date
        myDate = java.sql.Date.valueOf(tempDate);
        // write monday values
        guardSheet = writeMonday(myDate, guardSheet);
        tempDate = myDate.toLocalDate().plusDays(1); //get tuesday date
        myDate = java.sql.Date.valueOf(tempDate);
        if (mondayOtherRdBttn.isSelected())
        {
            guardSheet.getCellAt("AC6").setValue(supMondayTextField.getText());
        }
        else
        {
            guardSheet.getCellAt("AC6").setValue(defaultSUP);
        }
        // write tuesday values
        guardSheet = writeTuesday(myDate, guardSheet);        
        tempDate = myDate.toLocalDate().plusDays(1); //get wednesday date
        myDate = java.sql.Date.valueOf(tempDate);
       if (tuesdayOtherRdBttn.isSelected())
        {
            guardSheet.getCellAt("AQ6").setValue(supTuesdayTextField.getText());
        }
        else
        {
            guardSheet.getCellAt("AQ6").setValue(defaultSUP);
        }
       // write wednesday values
        guardSheet = writeWednesday(myDate, guardSheet);
        tempDate = myDate.toLocalDate().plusDays(1); //get thursday date
        myDate = java.sql.Date.valueOf(tempDate);
       if (wednesdayOtherRdBttn.isSelected())
        {
            guardSheet.getCellAt("B65").setValue(supWednesdayTextField.getText());
        }
        else
        {
            guardSheet.getCellAt("B65").setValue(defaultSUP);
        }
       // write thursday values
       guardSheet = writeThursday(myDate, guardSheet);
       tempDate = myDate.toLocalDate().plusDays(1); //get friday date
        myDate = java.sql.Date.valueOf(tempDate);
       if (thursdayOtherRdBttn.isSelected())
        {
            guardSheet.getCellAt("Q65").setValue(supThursdayTextField.getText());
        }
        else
        {
            guardSheet.getCellAt("Q65").setValue(defaultSUP);
        }
        // write friday values
       guardSheet = writeFriday(myDate, guardSheet);
       if (thursdayOtherRdBttn.isSelected())
        {
            guardSheet.getCellAt("AE65").setValue(supFridayTextField.getText());
        }
        else
        {
            guardSheet.getCellAt("AE65").setValue(defaultSUP);
        }
       
        String fileName = "roster " + startDate.getDayOfMonth() + "-" + startDate.getMonthValue() + "-" + startDate.getYear();
        comFunc.saveFile(guardSheet, fileName);
    }//GEN-LAST:event_exportButtonActionPerformed

    private Sheet writeSaturday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        System.out.println("write saturday function");
        final String saturdayDay = "H1";
        final String saturdayMonth = "J1";
        final String saturdayYear = "L1";
        String morningOnCall = null;
        String afternoonOnCall = null;
        
        ArrayList saturdayColumns = new ArrayList();
        saturdayColumns.add("B");
        saturdayColumns.add("C");
        saturdayColumns.add("D");
        saturdayColumns.add("E");
        saturdayColumns.add("F");
        saturdayColumns.add("G");
        saturdayColumns.add("H");
        saturdayColumns.add("I");
        saturdayColumns.add("J");
        saturdayColumns.add("K");
        Integer staffRow = 6;
        String selectedColumn;

        //Add saturday date
        LocalDate saturdayDate = inDate.toLocalDate();
        inSheet.getCellAt(saturdayDay).setValue(saturdayDate.getDayOfMonth());
        inSheet.getCellAt(saturdayMonth).setValue(saturdayDate.getMonthValue());
        inSheet.getCellAt(saturdayYear).setValue(saturdayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do {
                selectedColumn = saturdayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("17")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                Integer startRow = 0;
                Integer endRow = 0;
                for (int x = 0; x < 33; x = x + 1) 
                {
                    if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) 
                    {
                        startRow = Integer.valueOf(timeList[x][1]);
                        break;
                    }
                }
                for (int x = 0; x < 33; x = x + 1) 
                {
                    if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) 
                    {
                        endRow = Integer.valueOf(timeList[x][1]);
                        break;
                    }
                }
                //change background colour of cells
                if (startRow > 0) {
                    do {
                        String cell = selectedColumn.concat(startRow.toString());
                        if (tempGuard.getStartTime().getHour() >= 12) 
                        {
                            inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                            afternoonOnCall = tempGuard.getOnCall();
                        } 
                        else 
                        {
                            inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                            morningOnCall = tempGuard.getOnCall();
                        }
                        startRow++;
                    } while (startRow != endRow + 1);
                }
                count++;
            } while (count != guardShifts.size());
            
            inSheet.getCellAt("L6").setValue(morningOnCall);
            inSheet.getCellAt("M6").setValue(afternoonOnCall);
        } 
        catch (SQLException ex) {
            
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private Sheet writeSunday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        System.out.println("Write Sunday Function");
        final String sundayDay = "U1";
        final String sundayMonth = "W1";
        final String sundayYear = "Y1";
        String morningOnCall = null;
        String afternoonOnCall = null;
        
        ArrayList sundayColumns = new ArrayList();
        sundayColumns.add("O");
        sundayColumns.add("P");
        sundayColumns.add("Q");
        sundayColumns.add("R");
        sundayColumns.add("S");
        sundayColumns.add("T");
        sundayColumns.add("U");
        sundayColumns.add("V");
        sundayColumns.add("W");
        sundayColumns.add("X");
        Integer staffRow = 6;
        String selectedColumn;

        //Add Sunday date
        LocalDate sundayDate = inDate.toLocalDate();
        inSheet.getCellAt(sundayDay).setValue(sundayDate.getDayOfMonth());
        inSheet.getCellAt(sundayMonth).setValue(sundayDate.getMonthValue());
        inSheet.getCellAt(sundayYear).setValue(sundayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do {
                selectedColumn = sundayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("17")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                Integer startRow = 0;
                Integer endRow = 0;
                for (int x = 0; x < 33; x = x + 1) {
                    if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) {
                        startRow = Integer.valueOf(timeList[x][1]);
                        break;
                    }
                }
                for (int x = 0; x < 33; x = x + 1) {
                    if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) {
                        endRow = Integer.valueOf(timeList[x][1]);
                        break;
                    }
                }
                //change background colour of cells
                if (startRow > 0) {
                    do {
                        String cell = selectedColumn.concat(startRow.toString());
                        if (tempGuard.getStartTime().getHour() >= 12) 
                        {
                            inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                            afternoonOnCall = tempGuard.getOnCall();
                        } 
                        else 
                        {
                            inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                            morningOnCall = tempGuard.getOnCall();
                        }
                        startRow++;
                    } while (startRow != endRow + 1);
                }
                count++;
            } while (count != guardShifts.size());
            
            inSheet.getCellAt("Y6").setValue(morningOnCall);
            inSheet.getCellAt("Z6").setValue(afternoonOnCall);
        } catch (SQLException ex) 
        {
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private Sheet writeMonday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        System.out.println("write monday function");
        final String mondayDay = "AH1";
        final String mondayMonth = "AJ1";
        final String mondayYear = "AL1";
        String morningOnCall = null;
        String afternoonOnCall = null;

        ArrayList mondayColumns = new ArrayList();
        mondayColumns.add("AD");
        mondayColumns.add("AE");
        mondayColumns.add("AF");
        mondayColumns.add("AG");
        mondayColumns.add("AH");
        mondayColumns.add("AI");
        mondayColumns.add("AJ");
        mondayColumns.add("AK");
        mondayColumns.add("AL");
        mondayColumns.add("AM");
        Integer staffRow = 6;
        String selectedColumn;

        //Add Monday date
        LocalDate mondayDate = inDate.toLocalDate();
        inSheet.getCellAt(mondayDay).setValue(mondayDate.getDayOfMonth());
        inSheet.getCellAt(mondayMonth).setValue(mondayDate.getMonthValue());
        inSheet.getCellAt(mondayYear).setValue(mondayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do 
            {
                selectedColumn = mondayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("17")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                Integer startRow = 0;
                Integer endRow = 0;
                for (int x = 0; x < 33; x = x + 1) 
                {
                    if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) 
                    {
                        startRow = Integer.valueOf(timeList[x][1]);
                        break;
                    }
                }
                for (int x = 0; x < 33; x = x + 1) 
                {
                    if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) 
                    {
                        endRow = Integer.valueOf(timeList[x][1]);
                        break;
                    }
                }
                //change background colour of cells
                if (startRow > 0) 
                {
                    do 
                    {
                        String cell = selectedColumn.concat(startRow.toString());
                        if (tempGuard.getStartTime().getHour() >= 12) 
                        {
                            inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                            afternoonOnCall = tempGuard.getOnCall();
                        } 
                        else
                        {
                            inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                            morningOnCall = tempGuard.getOnCall();
                        }
                        startRow++;
                    } while (startRow != endRow + 1);
                }
                count++;
            } while (count != guardShifts.size());
            inSheet.getCellAt("AN6").setValue(morningOnCall);
            inSheet.getCellAt("AO6").setValue(afternoonOnCall);
        } 
        catch (SQLException ex) 
        {
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private Sheet writeTuesday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        System.out.println("write Tuesday function");
        final String tuesdayDay = "AV1";
        final String tuesdayMonth = "AX1";
        final String tuesdayYear = "AZ1";
        String morningOnCall = null;
        String afternoonOnCall = null;

        ArrayList tuesdayColumns = new ArrayList();
        tuesdayColumns.add("AR");
        tuesdayColumns.add("AS");
        tuesdayColumns.add("AT");
        tuesdayColumns.add("AU");
        tuesdayColumns.add("AV");
        tuesdayColumns.add("AW");
        tuesdayColumns.add("AX");
        tuesdayColumns.add("AY");
        tuesdayColumns.add("AZ");
        tuesdayColumns.add("BA");
        Integer staffRow = 6;
        String selectedColumn;
        
        //Add Tuesday date
        LocalDate tuesdayDate = inDate.toLocalDate();
        inSheet.getCellAt(tuesdayDay).setValue(tuesdayDate.getDayOfMonth());
        inSheet.getCellAt(tuesdayMonth).setValue(tuesdayDate.getMonthValue());
        inSheet.getCellAt(tuesdayYear).setValue(tuesdayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do
            {
                selectedColumn = tuesdayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("17")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                    Integer startRow = 0;
                    Integer endRow = 0;
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            startRow = Integer.valueOf(timeList[x][1]);
                            break;
                        }
                    }
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            endRow = Integer.valueOf(timeList[x][1]);
                            break;
                        }
                    }
                    //change background colour of cells
                    if (startRow > 0) 
                    {
                        do
                        {
                            String cell = selectedColumn.concat(startRow.toString());
                            if (tempGuard.getStartTime().getHour() >=12)
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                                afternoonOnCall = tempGuard.getOnCall();
                            }
                            else
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                                morningOnCall = tempGuard.getOnCall();
                            }
                            startRow++;
                        } while (startRow != endRow+1);
                    }
                count ++;
            } while (count != guardShifts.size());
            inSheet.getCellAt("BB6").setValue(morningOnCall);
            inSheet.getCellAt("BC6").setValue(afternoonOnCall);
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private Sheet writeWednesday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        System.out.println("write wednesday function");
        final String wednesdayDay = "G60";
        final String wednesdayMonth = "I60";
        final String wednesdayYear = "K60";
        String morningOnCall = null;
        String afternoonOnCall = null;

        ArrayList wednesdayColumns = new ArrayList();
        wednesdayColumns.add("C");
        wednesdayColumns.add("D");
        wednesdayColumns.add("E");
        wednesdayColumns.add("F");
        wednesdayColumns.add("G");
        wednesdayColumns.add("H");
        wednesdayColumns.add("I");
        wednesdayColumns.add("J");
        wednesdayColumns.add("K");
        wednesdayColumns.add("L");
        Integer staffRow = 65;
        String selectedColumn;
        
        //Add Wednesday date
        LocalDate wednesdayDate = inDate.toLocalDate();
        inSheet.getCellAt(wednesdayDay).setValue(wednesdayDate.getDayOfMonth());
        inSheet.getCellAt(wednesdayMonth).setValue(wednesdayDate.getMonthValue());
        inSheet.getCellAt(wednesdayYear).setValue(wednesdayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do
            {
                selectedColumn = wednesdayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("76")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                    Integer startRow = 0;
                    Integer endRow = 0;
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            startRow = Integer.valueOf(timeList[x][2]);
                            break;
                        }
                    }
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            endRow = Integer.valueOf(timeList[x][2]);
                            break;
                        }
                    }
                    //change background colour of cells
                    if (startRow > 0) 
                    {
                        do
                        {
                            String cell = selectedColumn.concat(startRow.toString());
                            if (tempGuard.getStartTime().getHour() >=12)
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                                afternoonOnCall = tempGuard.getOnCall();
                            }
                            else
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                                morningOnCall = tempGuard.getOnCall();
                            }
                            startRow++;
                        } while (startRow != endRow+1);
                    }
                count ++;
            } while (count != guardShifts.size());
            
            inSheet.getCellAt("M65").setValue(morningOnCall);
            inSheet.getCellAt("N65").setValue(afternoonOnCall);
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private Sheet writeThursday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        System.out.println("write Thursday function");
        final String thursdayDay = "V60";
        final String thursdayMonth = "X60";
        final String thursdayYear = "Z60";
        String morningOnCall = null;
        String afternoonOnCall = null;

        ArrayList thursdayColumns = new ArrayList();
        thursdayColumns.add("R");
        thursdayColumns.add("S");
        thursdayColumns.add("T");
        thursdayColumns.add("U");
        thursdayColumns.add("V");
        thursdayColumns.add("W");
        thursdayColumns.add("X");
        thursdayColumns.add("Y");
        thursdayColumns.add("Z");
        thursdayColumns.add("AA");
        Integer staffRow = 65;
        String selectedColumn;
        
        //Add Thursday date
        LocalDate thursdayDate = inDate.toLocalDate();
        inSheet.getCellAt(thursdayDay).setValue(thursdayDate.getDayOfMonth());
        inSheet.getCellAt(thursdayMonth).setValue(thursdayDate.getMonthValue());
        inSheet.getCellAt(thursdayYear).setValue(thursdayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do
            {
                selectedColumn = thursdayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("76")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                    Integer startRow = 0;
                    Integer endRow = 0;
                    for (int x = 0; x < 33; x = x + 1) {
                        //System.out.println(timeList[x][0]);
                        if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            startRow = Integer.valueOf(timeList[x][2]);
                            break;
                        }
                    }
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            endRow = Integer.valueOf(timeList[x][2]);
                            break;
                        }
                    }
                    //change background colour of cells
                    if (startRow > 0) 
                    {
                        do
                        {
                            String cell = selectedColumn.concat(startRow.toString());
                            if (tempGuard.getStartTime().getHour() >=12)
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                                afternoonOnCall = tempGuard.getOnCall();
                            }
                            else
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                                morningOnCall = tempGuard.getOnCall();
                            }
                            startRow++;
                        } while (startRow != endRow+1);
                    }
                count ++;
            } while (count != guardShifts.size());
            
            inSheet.getCellAt("AB65").setValue(morningOnCall);
            inSheet.getCellAt("AC65").setValue(afternoonOnCall);
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private Sheet writeFriday(java.sql.Date inDate, Sheet inSheet)
    {
        guardShifts.clear();
        String morningOnCall = null;
        String afternoonOnCall = null;
        System.out.println("write Friday function");
        final String fridayDay = "AJ60";
        final String fridayMonth = "AL60";
        final String fridayYear = "AN60";

        ArrayList fridayColumns = new ArrayList();
        fridayColumns.add("AF");
        fridayColumns.add("AG");
        fridayColumns.add("AH");
        fridayColumns.add("AI");
        fridayColumns.add("AJ");
        fridayColumns.add("AK");
        fridayColumns.add("AL");
        fridayColumns.add("AM");
        fridayColumns.add("AN");
        fridayColumns.add("AO");
        Integer staffRow = 65;
        String selectedColumn;
        
        //Add friday date
        LocalDate fridayDate = inDate.toLocalDate();
        inSheet.getCellAt(fridayDay).setValue(fridayDate.getDayOfMonth());
        inSheet.getCellAt(fridayMonth).setValue(fridayDate.getMonthValue());
        inSheet.getCellAt(fridayYear).setValue(fridayDate.getYear());
        String command = "select * from lifeguard where shift_date = \'" + inDate + "\' order by start_time";
        ResultSet result = null;
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_Date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                guardShifts.add(tempGuard);
            }
            int count = 0;
            do
            {
                selectedColumn = fridayColumns.get(count).toString();
                lifeguards tempGuard = guardShifts.get(count);
                inSheet.getCellAt(selectedColumn.concat(staffRow.toString())).setValue(tempGuard.getStaff1());
                inSheet.getCellAt(selectedColumn.concat("76")).setValue((comFunc.timeConvert(tempGuard.getStartTime()).concat(" - ")).concat(comFunc.timeConvert(tempGuard.getEndTime())));
                    Integer startRow = 0;
                    Integer endRow = 0;
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getStartTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            startRow = Integer.valueOf(timeList[x][2]);
                            break;
                        }
                    }
                    for (int x = 0; x < 33; x = x + 1) {
                        if (tempGuard.getEndTimeString().equalsIgnoreCase(timeList[x][0])) 
                        {
                            endRow = Integer.valueOf(timeList[x][2]);
                            break;
                        }
                    }
                    //change background colour of cells
                    if (startRow > 0) 
                    {
                        do
                        {
                            String cell = selectedColumn.concat(startRow.toString());
                            if (tempGuard.getStartTime().getHour() >=12)
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.yellow);
                                afternoonOnCall = tempGuard.getOnCall();
                            }
                            else
                            {
                                inSheet.getCellAt(cell).setBackgroundColor(Color.red);
                                morningOnCall = tempGuard.getOnCall();
                            }
                            startRow++;
                        } while (startRow != endRow+1);
                    }
                count ++;
            } while (count != guardShifts.size());
            
            inSheet.getCellAt("AP65").setValue(morningOnCall);
            inSheet.getCellAt("AQ65").setValue(afternoonOnCall);
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        return inSheet;
    }
    
    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboActionPerformed

    private void dateComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateComboItemStateChanged

    }//GEN-LAST:event_dateComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JButton exportButton;
    private javax.swing.JRadioButton fridayDefRdBttn;
    private javax.swing.ButtonGroup fridayGroup;
    private javax.swing.JRadioButton fridayOtherRdBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton mondayDefRdBttn;
    private javax.swing.ButtonGroup mondayGroup;
    private javax.swing.JRadioButton mondayOtherRdBttn;
    private javax.swing.JTextField supFridayTextField;
    private javax.swing.JTextField supMondayTextField;
    private javax.swing.JTextField supThursdayTextField;
    private javax.swing.JTextField supTuesdayTextField;
    private javax.swing.JTextField supWednesdayTextField;
    private javax.swing.JRadioButton thursdayDefRdBttn;
    private javax.swing.ButtonGroup thursdayGroup;
    private javax.swing.JRadioButton thursdayOtherRdBttn;
    private javax.swing.JRadioButton tuesdayDefRdBttn;
    private javax.swing.ButtonGroup tuesdayGroup;
    private javax.swing.JRadioButton tuesdayOtherRdBttn;
    private javax.swing.JRadioButton wednesdayDefRdBttn;
    private javax.swing.ButtonGroup wednesdayGroup;
    private javax.swing.JRadioButton wednesdayOtherRdBttn;
    // End of variables declaration//GEN-END:variables
}
