/*
 * Copyright 2016 james.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
/**
 *
 * @author james
 */
public class overview extends javax.swing.JDialog 
{
    main parent;
    dbConnection connection;
    commonFunctions comFunc;
    ArrayList<lts> ltsStaffShifts = new ArrayList<lts>();
    ArrayList<lifeguards> lifeguardShifts = new ArrayList<lifeguards>();
    ArrayList<isc> iscStaffShifts = new ArrayList<isc>();
    /**
     * Creates new form locationOverview
     */
    public overview(main inParent, dbConnection inConnection, commonFunctions inCommon) {
        super(inParent,true);
        initComponents();
        parent = inParent;
        connection = inConnection;
        comFunc = inCommon;
        loadData();
        firstLoad();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namebuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lifeguardList = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ltsList = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        iscList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lifeguardStartTimeLbl = new javax.swing.JLabel();
        lifeguardEndTimeLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        staffLbl = new javax.swing.JLabel();
        lifeguardStaffLbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lifeguardOnCallLbl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lifeguardLocationLbl = new javax.swing.JLabel();
        ltsEndDateLbl = new javax.swing.JLabel();
        ltsLocationLbl = new javax.swing.JLabel();
        ltsStaffLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ltsStartDateLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ltsEndTimeLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ltsStartTimeLbl = new javax.swing.JLabel();
        iscStartTimeLbl = new javax.swing.JLabel();
        iscEndTimeLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        staffLbl1 = new javax.swing.JLabel();
        iscStaff1Lbl = new javax.swing.JLabel();
        iscStaff2Lbl = new javax.swing.JLabel();
        iscStaff3Lbl = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        iscOnCallLbl = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        iscLocationLbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dateCombo = new javax.swing.JComboBox<>();
        updateBttn = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        iscStaff4Lbl = new javax.swing.JLabel();
        endDateCombo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        lifeguardStartTimeLbl1 = new javax.swing.JLabel();
        lifeguardEndTimeLbl1 = new javax.swing.JLabel();
        iscEndTimeLbl1 = new javax.swing.JLabel();
        iscStartTimeLbl1 = new javax.swing.JLabel();
        ltsEndTimeLbl1 = new javax.swing.JLabel();
        ltsStartTimeLbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        allRadioButton = new javax.swing.JRadioButton();
        nameRadioButton = new javax.swing.JRadioButton();
        nameTxtFld = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lifeguard");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LTS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lifeguardList.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lifeguardList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lifeguardListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lifeguardList);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ltsList.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ltsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ltsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ltsList);

        iscList.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        iscList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                iscListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(iscList);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ISC");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lifeguardStartTimeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardStartTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lifeguardEndTimeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardEndTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel5.setText("End Time:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel4.setText("Start Time:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel7.setText("Location:");

        staffLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        staffLbl.setText("Staff:");

        lifeguardStaffLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardStaffLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel6.setText("On Call:");

        lifeguardOnCallLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardOnCallLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lifeguardLocationLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardLocationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ltsEndDateLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsEndDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ltsLocationLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsLocationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ltsStaffLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsStaffLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel8.setText("Staff:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel9.setText("Location:");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel10.setText("End Date:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel11.setText("Start Date:");

        ltsStartDateLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsStartDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setText("End Time:");

        ltsEndTimeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsEndTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setText("Start Time:");

        ltsStartTimeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsStartTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscStartTimeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscStartTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscEndTimeLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscEndTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel14.setText("End Time:");

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel15.setText("Location:");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel16.setText("Start Time:");

        staffLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        staffLbl1.setText("Staff:");

        iscStaff1Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscStaff1Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscStaff2Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscStaff2Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscStaff3Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscStaff3Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel17.setText("On Call:");

        iscOnCallLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscOnCallLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscLocationLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscLocationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel18.setText("Date:");

        dateCombo.setEditable(true);
        dateCombo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });

        updateBttn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        updateBttn.setText("Update");
        updateBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBttnActionPerformed(evt);
            }
        });

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        iscStaff4Lbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscStaff4Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        endDateCombo.setEditable(true);
        endDateCombo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        endDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateComboActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel19.setText("End Date:");

        lifeguardStartTimeLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardStartTimeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lifeguardEndTimeLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lifeguardEndTimeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscEndTimeLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscEndTimeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        iscStartTimeLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        iscStartTimeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ltsEndTimeLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsEndTimeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ltsStartTimeLbl1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ltsStartTimeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        namebuttonGroup.add(allRadioButton);
        allRadioButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        allRadioButton.setSelected(true);
        allRadioButton.setText("All");
        allRadioButton.setEnabled(false);
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioButtonActionPerformed(evt);
            }
        });

        namebuttonGroup.add(nameRadioButton);
        nameRadioButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        nameRadioButton.setText("Name");
        nameRadioButton.setEnabled(false);
        nameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRadioButtonActionPerformed(evt);
            }
        });

        nameTxtFld.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        nameTxtFld.setEnabled(false);

        jLabel20.setText("LTS supports name filtering only");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(staffLbl)
                                .addGap(7, 7, 7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lifeguardLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lifeguardStaffLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lifeguardEndTimeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(lifeguardStartTimeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lifeguardStartTimeLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(lifeguardEndTimeLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lifeguardOnCallLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel17)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iscOnCallLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iscStartTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(staffLbl1)
                                        .addGap(7, 7, 7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(iscLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iscStaff1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iscStaff2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iscStaff3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(iscStaff4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(iscEndTimeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(iscStartTimeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iscEndTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ltsEndDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ltsLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ltsStaffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ltsStartDateLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(ltsEndTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ltsEndTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ltsStartTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ltsStartTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(updateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(allRadioButton)
                                                    .addComponent(nameRadioButton)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(endDateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dateCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel19)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(1, 1, 1)
                                .addComponent(endDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(allRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameRadioButton)
                                .addGap(2, 2, 2)
                                .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ltsStartTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ltsStartTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ltsEndTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(ltsEndTimeLbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(ltsStartDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(ltsEndDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(ltsLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(ltsStaffLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel16)
                                                    .addComponent(iscStartTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(iscEndTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(iscStartTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(iscEndTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(iscLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iscStaff1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iscStaff2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iscStaff3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iscStaff4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(58, 58, 58)
                                                .addComponent(staffLbl1))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(lifeguardStartTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lifeguardStartTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(lifeguardEndTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lifeguardEndTimeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lifeguardLocationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lifeguardStaffLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(32, 32, 32)
                                                .addComponent(staffLbl)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lifeguardOnCallLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel6)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iscOnCallLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel17)))))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBttnActionPerformed
        iscStaffShifts.clear();
        lifeguardShifts.clear();
        lifeguardList();
        iscList();
        ltsList();
    }//GEN-LAST:event_updateBttnActionPerformed

    private void lifeguardListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lifeguardListValueChanged
        try {
        lifeguards selectedShift = (lifeguards)lifeguardList.getSelectedValue();
        lifeguardStartTimeLbl.setText((selectedShift.getStartTime()).toString());
        lifeguardStartTimeLbl1.setText(comFunc.timeConvert(selectedShift.getStartTime()));
        lifeguardEndTimeLbl.setText((selectedShift.getEndTime()).toString());
        lifeguardEndTimeLbl1.setText(comFunc.timeConvert(selectedShift.getEndTime()));
        lifeguardStaffLbl1.setText(selectedShift.getStaff1());
        lifeguardLocationLbl.setText(selectedShift.getLocation());
        lifeguardOnCallLbl.setText(selectedShift.getOnCall());
        }
        catch (Exception ex)
        {
            System.out.println("Lifeguard Selection Change\n" + ex);
        }
    }//GEN-LAST:event_lifeguardListValueChanged

    private void ltsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ltsListValueChanged
        try {
            lts selectedShift = (lts) ltsList.getSelectedValue();
            ltsStartTimeLbl.setText((selectedShift.getStartTime()).toString());
            ltsStartTimeLbl1.setText(comFunc.timeConvert(selectedShift.getStartTime()));
            ltsEndTimeLbl.setText((selectedShift.getEndTime()).toString());
            ltsEndTimeLbl1.setText(comFunc.timeConvert(selectedShift.getEndTime()));
            ltsStaffLbl.setText(selectedShift.getStaff());
            ltsStartDateLbl.setText(comFunc.formatDate(selectedShift.getStartDate().toLocalDate()));
            ltsEndDateLbl.setText(comFunc.formatDate(selectedShift.getEndDate().toLocalDate()));
            ltsLocationLbl.setText(selectedShift.getLocation());
        } catch (Exception ex) {
            System.out.println("lts selection change\n" + ex);
        }
    }//GEN-LAST:event_ltsListValueChanged

    private void iscListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_iscListValueChanged
        try {
            isc selectedShift = (isc) iscList.getSelectedValue();
            iscStartTimeLbl.setText((selectedShift.getStartTime()).toString());
            iscStartTimeLbl1.setText(comFunc.timeConvert(selectedShift.getStartTime()));
            iscEndTimeLbl.setText((selectedShift.getEndTime()).toString());
            iscEndTimeLbl1.setText(comFunc.timeConvert(selectedShift.getEndTime()));
            iscStaff1Lbl.setText(selectedShift.getStaff1());
            iscStaff2Lbl.setText(selectedShift.getStaff2());
            iscStaff3Lbl.setText(selectedShift.getStaff3());
            iscStaff4Lbl.setText(selectedShift.getStaff4());
            iscLocationLbl.setText(selectedShift.getLocation());
            iscOnCallLbl.setText(selectedShift.getOnCall());
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_iscListValueChanged

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboActionPerformed

    private void endDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void allRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioButtonActionPerformed
        nameTxtFld.setEnabled(false);
    }//GEN-LAST:event_allRadioButtonActionPerformed

    private void nameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRadioButtonActionPerformed
        nameTxtFld.setEnabled(true);
    }//GEN-LAST:event_nameRadioButtonActionPerformed

    private void firstLoad()
    {
        if (parent.isSupervisor())
        {
            allRadioButton.setEnabled(true);
            nameRadioButton.setEnabled(true);
        }
    }
    
    private void lifeguardList ()
    {
        // Lifeguard list setup
        String command = null;
        
        if (parent.isSupervisor())
        {
            if (allRadioButton.isSelected() && ((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                command = "select * from lifeguard";
            }
            else if (allRadioButton.isSelected() && !((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                if (((String)endDateCombo.getSelectedItem()).equalsIgnoreCase("None"))
                {
                    command = "select * from lifeguard where shift_date = \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\'";
                }
                else
                {
                    command = "select * from lifeguard where shift_date between  \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\' and \'" + comFunc.dateSwitch((String)endDateCombo.getSelectedItem()) + "\'";
                }
            }
            else if (nameRadioButton.isSelected() && ((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                command = "select * from lifeguard where staff1 = \'" + nameTxtFld.getText() + "\'";
            }
            else if (nameRadioButton.isSelected() && !((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                if (((String)endDateCombo.getSelectedItem()).equalsIgnoreCase("None"))
                {
                    command = "select * from lifeguard where (staff1 = \'" + nameTxtFld.getText()+"\' or onCall = \'" + nameTxtFld.getText() +"\') and shift_date = \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\'";
                }
                else
                {
                    command = "select * from lifeguard where (staff1 = \'" + nameTxtFld.getText() + "\' or onCall = \'" + nameTxtFld.getText() + "\') and shift_date between  \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\' and \'" + comFunc.dateSwitch((String)endDateCombo.getSelectedItem()) + "\'";
                }
            }
        }
        else
        {
            if (((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                command = "select * from lifeguard where staff1 = \'" + parent.getUser() + "\' or onCall = \'" + parent.getUser() + "\'";
            }
            else if (!((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                if (((String)endDateCombo.getSelectedItem()).equalsIgnoreCase("None"))
                {
                    command = "select * from lifeguard where (staff1 = \'" + parent.getUser() + "\' or onCall = \'" + parent.getUser() + "\') and shift_date = \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\'";
                }
                else
                {
                    command = "select * from lifeguard where (staff1 = \'" + parent.getUser() + "\' or onCall = \'" + parent.getUser() + "\') and shift_date between \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\' and \'" + comFunc.dateSwitch((String)endDateCombo.getSelectedItem()) + "\'";
                }
            }
        }
        
        ResultSet result = null;
        
        System.out.println("lifeguard list change\n " + command);
        try {
            result = connection.lookup(command);
            while (result.next()) {
                lifeguards tempGuard = new lifeguards(result.getInt("ID"), result.getDate("shift_date"), result.getTime("start_time"), result.getTime("end_time"), result.getString("location"), result.getString("staff1"), result.getString("onCall"));
                lifeguardShifts.add(tempGuard);
            }
            lifeguardList.setListData(lifeguardShifts.toArray());
            
            if (!lifeguardShifts.isEmpty())
            {
                lifeguardList.setSelectedIndex(1);
            }
        }
        catch (SQLException ex) 
        {
            System.out.println("lifeguard load data\n" + ex);
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }
    
    private void ltsList ()
    {
        // LTS list setup
        String command = null;
        ltsStaffShifts.clear();
        if (parent.isSupervisor())
        {
            if (allRadioButton.isSelected())
            {
                command = "select * from LTS_Shift";
            }
            else
            {
                command = "select * from LTS_Shift where staff = \'" + nameTxtFld.getText() + "\'";
            }
        }
        else
        {
            command = "select * from LTS_Shift where staff = \'" + parent.getUser() + "\'";
        }
        System.out.println("lts list change\n " + command);
        ResultSet result = connection.lookup(command);
        try {
            while (result.next()) {
                lts ltsShift = new lts(result.getInt("ID"), result.getString("staff"), result.getString("shift_day"), result.getString("location"), result.getTime("start_time"), result.getTime("end_time"), result.getDate("start_date"), result.getDate("end_date"));
                ltsStaffShifts.add(ltsShift);
            }
            ltsList.setListData(ltsStaffShifts.toArray());
            if (!ltsStaffShifts.isEmpty())
            {
                ltsList.setSelectedIndex(0);
            }
        } catch (SQLException ex) {
            System.out.println("lts load data\n" + ex);
        }
    }
    
    private void iscList()
    {
        String command = null;
        
        if (parent.isSupervisor())
        {
            if (allRadioButton.isSelected() && ((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                command = "select * from isc";
            }
            else if (allRadioButton.isSelected() && !((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                if (((String)endDateCombo.getSelectedItem()).equalsIgnoreCase("None"))
                {
                    command = "select * from isc where shift_date = \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\'";
                }
                else
                {
                    command = "select * from isc where shift_date between  \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\' and \'" + comFunc.dateSwitch((String)endDateCombo.getSelectedItem()) + "\'";
                }
            }
            else if (nameRadioButton.isSelected() && ((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                command = "select * from isc where staff1 = \'" + parent.getUser() + "\' or staff2 = \'" + parent.getUser() + "\' or staff3 = \'" + parent.getUser() + "\' or staff4 = \'" + parent.getUser() + "\'or onCall = \'" + parent.getUser() + "\'";
            }
            else if (nameRadioButton.isSelected() && !((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                if (((String)endDateCombo.getSelectedItem()).equalsIgnoreCase("None"))
                {
                    command = "select * from isc where (staff1 = \'" + parent.getUser() + "\' or staff2 = \'" + parent.getUser() + "\' or staff3 = \'" + parent.getUser() + "\' or staff4 = \'" + parent.getUser() + "\'or onCall = \'" + parent.getUser() + "\') and shift_date = \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\'";
                }
                else
                {
                    command = "select * from isc where (staff1 = \'" + parent.getUser() + "\' or staff2 = \'" + parent.getUser() + "\' or staff3 = \'" + parent.getUser() + "\' or staff4 = \'" + parent.getUser() + "\'or onCall = \'" + parent.getUser() + "\') and shift_date between  \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\' and \'" + comFunc.dateSwitch((String)endDateCombo.getSelectedItem()) + "\'";
                }
            }
        }
        else
        {
            if (((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                command = "select * from isc where staff1 = \'" + parent.getUser() + "\' or staff2 = \'" + parent.getUser() + "\' or staff3 = \'" + parent.getUser() + "\' or staff4 = \'" + parent.getUser() + "\'or onCall = \'" + parent.getUser() + "\'";
            }
            else if (!((String)dateCombo.getSelectedItem()).equalsIgnoreCase("All"))
            {
                if (((String)endDateCombo.getSelectedItem()).equalsIgnoreCase("None"))
                {
                    command = "select * from isc where (staff1 = \'" + parent.getUser() + "\' or staff2 = \'" + parent.getUser() + "\' or staff3 = \'" + parent.getUser() + "\' or staff4 = \'" + parent.getUser() + "\'or onCall = \'" + parent.getUser() + "\') and shift_date = \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\'";
                }
                else
                {
                    command = "select * from isc where (staff1 = \'" + parent.getUser() + "\' or staff2 = \'" + parent.getUser() + "\' or staff3 = \'" + parent.getUser() + "\' or staff4 = \'" + parent.getUser() + "\'or onCall = \'" + parent.getUser() + "\') and shift_date between \'" + comFunc.dateSwitch((String)dateCombo.getSelectedItem()) + "\' and \'" + comFunc.dateSwitch((String)endDateCombo.getSelectedItem()) + "\'";
                }
            }
        }
        
        System.out.println("isc list change\n " + command);
        ResultSet returned = connection.lookup(command);
        try {
            while (returned.next()) {
                isc tempISC = new isc(returned.getInt("ID"), returned.getDate("shift_Date"), returned.getTime("start_time"), returned.getTime("end_time"), returned.getString("location"), returned.getString("staff1"), returned.getString("staff2"), returned.getString("staff3"), returned.getString("staff4"), returned.getString("onCall"));
                iscStaffShifts.add(tempISC);
            }
            iscList.setListData(iscStaffShifts.toArray());
            if (!iscStaffShifts.isEmpty()) {
                iscList.setSelectedIndex(0);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
    }
    
    private void loadData ()
    {
        dateCombo.addItem("All");
        endDateCombo.addItem("None");
        LocalDate manipDate = LocalDate.now();
        int count = 45;
        while (count > 0)
        {
            dateCombo.addItem(comFunc.minusDaysFormated(manipDate, count));
            if (count <= 15 && count >= 0)
            {
                endDateCombo.addItem(comFunc.minusDaysFormated(manipDate, count));
            }
            count--;
        }
        while (count < 45)
        {
            count++;
            if (count < 45)
            {
                dateCombo.addItem(comFunc.plusDaysFormated(manipDate, count));
            }
            endDateCombo.addItem(comFunc.plusDaysFormated(manipDate, count));
        }
        
        ltsList();
        dateCombo.setSelectedItem("All");
        iscList();
        lifeguardList();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.JComboBox<String> dateCombo;
    private javax.swing.JComboBox<String> endDateCombo;
    private javax.swing.JLabel iscEndTimeLbl;
    private javax.swing.JLabel iscEndTimeLbl1;
    private javax.swing.JList iscList;
    private javax.swing.JLabel iscLocationLbl;
    private javax.swing.JLabel iscOnCallLbl;
    private javax.swing.JLabel iscStaff1Lbl;
    private javax.swing.JLabel iscStaff2Lbl;
    private javax.swing.JLabel iscStaff3Lbl;
    private javax.swing.JLabel iscStaff4Lbl;
    private javax.swing.JLabel iscStartTimeLbl;
    private javax.swing.JLabel iscStartTimeLbl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lifeguardEndTimeLbl;
    private javax.swing.JLabel lifeguardEndTimeLbl1;
    private javax.swing.JList lifeguardList;
    private javax.swing.JLabel lifeguardLocationLbl;
    private javax.swing.JLabel lifeguardOnCallLbl;
    private javax.swing.JLabel lifeguardStaffLbl1;
    private javax.swing.JLabel lifeguardStartTimeLbl;
    private javax.swing.JLabel lifeguardStartTimeLbl1;
    private javax.swing.JLabel ltsEndDateLbl;
    private javax.swing.JLabel ltsEndTimeLbl;
    private javax.swing.JLabel ltsEndTimeLbl1;
    private javax.swing.JList ltsList;
    private javax.swing.JLabel ltsLocationLbl;
    private javax.swing.JLabel ltsStaffLbl;
    private javax.swing.JLabel ltsStartDateLbl;
    private javax.swing.JLabel ltsStartTimeLbl;
    private javax.swing.JLabel ltsStartTimeLbl1;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.ButtonGroup namebuttonGroup;
    private javax.swing.JLabel staffLbl;
    private javax.swing.JLabel staffLbl1;
    private javax.swing.JButton updateBttn;
    // End of variables declaration//GEN-END:variables
}
