/*
 * Copyright 2016 james.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.text.ParseException;
//import java.text.SimpleDateFormat;
//import java.time.LocalDate;
//import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author james
 */
public class removeAvailability extends javax.swing.JDialog {
    main parent;
    dbConnection connection;
    ArrayList<availability> availList = new ArrayList<availability>();
    int ID;

    /**
     * Creates new form addAvailability
     */
public removeAvailability(main inParent, dbConnection inConnection) {
        super(inParent, true);
        initComponents();
        parent = inParent;
        connection = inConnection;
        loadData();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availabilityButtonGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        removeBttn = new javax.swing.JButton();
        closeBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        availabilityList = new javax.swing.JList();
        completionTckbx = new javax.swing.JCheckBox();
        departmentLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();
        allRadioButton = new javax.swing.JRadioButton();
        nameRadioButton = new javax.swing.JRadioButton();
        nameTxtFld = new javax.swing.JTextField();
        lookupButton = new javax.swing.JButton();
        dateTxtFld = new javax.swing.JTextField();
        dateRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Availability");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel2.setText("Department:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel3.setText("Location:");

        removeBttn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        removeBttn.setText("Remove Availability");
        removeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBttnActionPerformed(evt);
            }
        });

        closeBttn.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        closeBttn.setText("Close");
        closeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBttnActionPerformed(evt);
            }
        });

        availabilityList.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        availabilityList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        availabilityList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                availabilityListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(availabilityList);

        completionTckbx.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        completionTckbx.setText("Close On Completion");

        departmentLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        locationLbl.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        availabilityButtonGroup.add(allRadioButton);
        allRadioButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        allRadioButton.setSelected(true);
        allRadioButton.setText("All");
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioButtonActionPerformed(evt);
            }
        });

        availabilityButtonGroup.add(nameRadioButton);
        nameRadioButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        nameRadioButton.setText("Name");
        nameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRadioButtonActionPerformed(evt);
            }
        });

        nameTxtFld.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        nameTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTxtFld.setEnabled(false);
        nameTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTxtFldKeyPressed(evt);
            }
        });

        lookupButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        lookupButton.setText("Lookup");
        lookupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupButtonActionPerformed(evt);
            }
        });

        dateTxtFld.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dateTxtFld.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dateTxtFld.setEnabled(false);
        dateTxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dateTxtFldKeyPressed(evt);
            }
        });

        availabilityButtonGroup.add(dateRadioButton);
        dateRadioButton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        dateRadioButton.setText("Week Starting");
        dateRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameRadioButton))
                            .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(completionTckbx))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(closeBttn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lookupButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(departmentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(locationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(removeBttn)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(departmentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(locationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(completionTckbx, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allRadioButton)
                            .addComponent(nameRadioButton)
                            .addComponent(dateRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBttn)
                    .addComponent(removeBttn)
                    .addComponent(lookupButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBttnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBttnActionPerformed

    private void removeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBttnActionPerformed
        
        if (JOptionPane.showConfirmDialog(parent, "Confirm to continue",
                "",
                JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION)
        {
            String command = "delete from availability where ID = \'" + ID + "\'";
            int status = connection.updateShift(command);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(parent, "Availability Removal Successfull", "", JOptionPane.INFORMATION_MESSAGE);
                if (completionTckbx.isSelected())
                {
                    dispose();
                }
                else
                {
                    loadData();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(parent, "Unable To Remove Availability", "", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_removeBttnActionPerformed

    private void availabilityListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_availabilityListValueChanged
        try
        {
            availability selectedAvailability = (availability)availabilityList.getSelectedValue();
            departmentLbl.setText(selectedAvailability.getDepartment());
            locationLbl.setText(selectedAvailability.getLocation());
            ID = selectedAvailability.getID();
        }
        catch (Exception ex)
        {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_availabilityListValueChanged

    private void nameTxtFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtFldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            lookupButton.doClick();
        }
    }//GEN-LAST:event_nameTxtFldKeyPressed

    private void lookupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lookupButtonActionPerformed

    private void dateTxtFldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateTxtFldKeyPressed
if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            lookupButton.doClick();
        }
    }//GEN-LAST:event_dateTxtFldKeyPressed

    private void nameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRadioButtonActionPerformed
        nameTxtFld.setEnabled(true);
        dateTxtFld.setEnabled(false);
    }//GEN-LAST:event_nameRadioButtonActionPerformed

    private void allRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioButtonActionPerformed
        nameTxtFld.setEnabled(false);
        dateTxtFld.setEnabled(false);
    }//GEN-LAST:event_allRadioButtonActionPerformed

    private void dateRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateRadioButtonActionPerformed
        dateTxtFld.setEnabled(true);
        nameTxtFld.setEnabled(false);
    }//GEN-LAST:event_dateRadioButtonActionPerformed

    private void loadData ()
    {
        availList.clear();
        availabilityList.setListData(availList.toArray());
        String command = null;
        if (parent.isSupervisor())
        {
            if (allRadioButton.isSelected())
            {
                command = "select * from availability";
            }
            else if (nameRadioButton.isSelected())
            {
                command = "select * from availability where username = \'" + nameTxtFld.getText() + "\'";
            }
            else
            {
                command = "select * from availability where weekStarting = \'";
            }
        }
        else
        {
            command = "select * from availability where username = \'" + parent.getUser() + "\'";
        }
        
        try
        {
            ResultSet returned = connection.lookup(command);
            
            while (returned.next())
            {
                // add availability entries to list
                availability tempAvailability = new availability(returned.getInt("ID"), returned.getString("username"), returned.getString("monday"), returned.getString("tuesday"), returned.getString("wednesday"), returned.getString("thursday"), returned.getString("friday"), returned.getString("saturday"), returned.getString("sunday"), returned.getString("department"), returned.getString("location"), returned.getDate("weekStarting"));
                availList.add(tempAvailability);
            }
            availabilityList.setListData(availList.toArray());
        }
        catch (SQLException ex)
        {
            System.out.println(ex);
        }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.ButtonGroup availabilityButtonGroup;
    private javax.swing.JList availabilityList;
    private javax.swing.JButton closeBttn;
    private javax.swing.JCheckBox completionTckbx;
    private javax.swing.JRadioButton dateRadioButton;
    private javax.swing.JTextField dateTxtFld;
    private javax.swing.JLabel departmentLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel locationLbl;
    private javax.swing.JButton lookupButton;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JButton removeBttn;
    // End of variables declaration//GEN-END:variables
}
